service: upschool-teacher
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  region: ap-south-1
  stage: ${opt:stage}
  environment:
    DB_PREFIX: ${self:provider.stage}_
    ACCESS_KEY_ID: ${file(config/${self:provider.stage}-config.yml):data.config.accessKeyId}
    SECRET_ACCESS_KEY: ${file(config/${self:provider.stage}-config.yml):data.config.secretAccessKey}
    REGION: ${self:provider.region}
    NODE_ENV: ${self:provider.stage}
    BUCKET_NAME: ${self:provider.stage}-upschool
    SECRET_KEY: ${file(config/${self:provider.stage}-config.yml):data.randomSecretKey.secretKey}    
    SEND_OTP_ARN: ${file(config/${self:provider.stage}-config.yml):data.sendOtpArn.arn}
    MP_APP_ID: ${file(config/${self:provider.stage}-config.yml):data.mathPix.MP_APP_ID}
    MP_APP_KEY: ${file(config/${self:provider.stage}-config.yml):data.mathPix.MP_APP_KEY}
    PDF_GENERATION_URL: ${file(config/${self:provider.stage}-config.yml):data.pdfMake.generate_url}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:CreateTable
          Resource:
            - "*"
functions:
  backend-lambda:
    handler: handler.upschoolTeacherServer
    events:
      - http:
          path: /v1/login
          method: POST
          cors: true
      - http:
          path: /v1/logout
          method: POST
          cors: true
      - http:
          path: /v1/loginWithOTP
          method: POST
          cors: true
      - http:
          path: /v1/validateOTP
          method: POST
          cors: true  
      - http:
          path: /v1/changePassword
          method: POST
          cors: true  
      - http:
          path: /v1/resetOrCreatePassword
          method: POST
          cors: true  
      - http:
          path: /v1/fetchUnitsandChaptersBasedonSubjects
          method: POST
          cors: true 
      - http:
          path: /v1/fetchTopicsBasedonChapter
          method: POST
          cors: true  
      - http:
          path: /v1/fetchDigicardsBasedonTopic
          method: POST
          cors: true  
      - http:
          path: /v1/fetchIndividualDigiCard
          method: POST
          cors: true  
      - http:
          path: /v1/fetchRelatedDigiCards
          method: POST
          cors: true  
      - http:
          path: /v1/fetchAllStudents
          method: POST
          cors: true   
      - http:
          path: /v1/chapterUnlock
          method: POST
          cors: true  
      - http:
          path: /v1/topicUnlock
          method: POST
          cors: true   
      - http:
          path: /v1/fetchTeacherClasses
          method: POST
          cors: true  
      - http:
          path: /v1/fetchTeacherSectionsBasedonClass
          method: POST
          cors: true  
      - http:
          path: /v1/fetchTeacherSubjectsBasedonSection
          method: POST
          cors: true  
      - http:
          path: /v1/fetchTopicAndNoOfQuestions
          method: POST
          cors: true  
      - http:
          path: /v1/unlockChapterPreLearning
          method: POST
          cors: true
      - http:
          path: /v1/addDigicardExtension
          method: POST
          cors: true  
      - http:
          path: /v1/digicardUnlock
          method: POST
          cors: true  
      - http:
          path: /v1/fetchAvailableNumOfQuestions
          method: POST
          cors: true 
      - http:
          path: /v1/archivedActiveTopicsInChapter
          method: POST
          cors: true 
      - http:
          path: /v1/getPreGrantedTeacherPermissions
          method: POST
          cors: true 
      - http:
          path: /v1/fetchAllPreTopicDigicards
          method: POST
          cors: true 
      - http:
          path: /v1/generatePrePostQuiz
          method: POST
          cors: true 
      - http:
          path: /v1/fetchAllPostTopicDigicards
          method: POST
          cors: true 
      - http:
          path: /v1/getPostGrantedTeacherPermissions
          method: POST
          cors: true 
      - http:
          path: /v1/fetchDigicardExtension
          method: POST
          cors: true 
      - http:
          path: /v1/reArrangeDigiCardOrder
          method: POST
          cors: true 
      - http:
          path: /v1/toggleDigicardsInTopic
          method: POST
          cors: true 
      - http:
          path: /v1/fetchDigiCardstoReorder
          method: POST
          cors: true 
      - http:
          path: /v1/fetchQuestionSourceandChapters
          method: POST
          cors: true 
      - http:
          path: /v1/fetchAllBluePrints
          method: POST
          cors: true 
      - http:
          path: /v1/fetchTopicsBasedonChapters
          method: POST
          cors: true 
      - http:
          path: /v1/fetchConceptsBasedonTopics
          method: POST
          cors: true 
      - http:
          path: /v1/fetchBlueprintById
          method: POST
          cors: true 
      - http:
          path: /v1/fetchQuestionBasedOnBlueprint
          method: POST
          cors: true 
      - http:
          path: /v1/addTestQuestionPaper
          method: POST
          cors: true 
      - http:
          path: /v1/fetchTestQuestionPapersBasedonStatus
          method: POST
          cors: true 
      - http:
          path: /v1/fetchQuestionBasedOnConcept
          method: POST
          cors: true
      - http:
          path: /v1/addClassTest
          method: POST
          cors: true
      - http:
          path: /v1/fetchClassTestsBasedonStatus
          method: POST
          cors: true
      - http:
          path: /v1/validateQuestionPaperName
          method: POST
          cors: true
      - http:
          path: /v1/sendScannerLink
          method: POST
          cors: true
      - http:
          path: /v1/sendOTPForScanning
          method: POST
          cors: true
      - http:
          path: /v1/validateOTPForScanning
          method: POST
          cors: true
      - http:
          path: /v1/fetchQuestionsBasedonQuestionPaper
          method: POST
          cors: true          
      - http:
          path: /v1/fetchSignedURLForAnswers
          method: POST
          cors: true
      - http:
          path: /v1/uploadAnswerSheets
          method: POST
          cors: true
      - http:
          path: /v1/fetchClassTestById
          method: POST
          cors: true
      - http:
          path: /v1/startEvaluation
          method: POST
          cors: true
      - http:
          path: /v1/viewTestQuestionPaper
          method: POST
          cors: true
      - http:
          path: /v1/toggleQuestionPaper
          method: POST
          cors: true
      - http:
          path: /v1/getStudentsBasedOnSection
          method: POST
          cors: true
      - http:
          path: /v1/getStudentResultData
          method: POST
          cors: true
      - http:
          path: /v1/updateStudentMarks
          method: POST
          cors: true
      - http:
          path: /v1/resetEvaluationStatus
          method: POST
          cors: true
      - http:
          path: /v1/toggleClassTestStatus
          method: POST
          cors: true
      - http:
          path: /v1/checkDuplicateQuizName
          method: POST
          cors: true 
      - http:
          path: /v1/toggleQuizStatus
          method: POST
          cors: true 
      - http:
          path: /v1/fetchQuizBasedonStatus
          method: POST
          cors: true 
      - http:
          path: /v1/fetchSignedURLForQuizAnswers
          method: POST
          cors: true
      - http:
          path: /v1/uploadQuizAnswerSheets
          method: POST
          cors: true
      - http:
          path: /v1/fetchQuizTemplates
          method: POST
          cors: true
      - http:
          path: /v1/resetQuizEvaluationStatus
          method: POST
          cors: true
      - http:
          path: /v1/getStudentQuizResultData
          method: POST
          cors: true
      - http:
          path: /v1/updateStudentQuizMarks
          method: POST
          cors: true
      - http:
          path: /v1/startQuizEvaluation
          method: POST
          cors: true
      - http:
          path: /v1/viewQuizQuestionPaper
          method: POST
          cors: true
      - http:
          path: /v1/createSchoolAdmin
          method: POST
          cors: true
      - http:
          path: /v1/updateSchoolAdmin
          method: POST
          cors: true
      - http:
          path: /v1/fetchAssessmentSummary
          method: POST
          cors: true
      - http:
          path: /v1/toggleSchoolAdminStatus
          method: POST
          cors: true    